enum Icons {
  sandwich = "eva:menu-outline",
  doubleArrowRight = "eva:arrowhead-right-outline",
  doubleArrowLeft = "eva:arrowhead-left-outline",
  settings = "eva:settings-fill",
  gridView = "eva:grid-outline",
  moreHorizontal = "eva:more-horizontal-fill",
  arrowDown = "eva:arrow-ios-downward-outline",
  arrowRight = "eva:arrow-ios-forward-outline",
  arrowDownFilled = "eva:caret-down",
  arrowRightFilled = "eva:caret-forward",
  check = "eva:checkmark-outline",
  circle = "famicons:ellipse",
  forkCode = "eva:git-network-outline",
  star = "eva:star-outline",
  eye = "eva:eye-outline",
  code = "eva:code-outline",
  link = "eva:link-outline",
  add = "eva:plus-outline",
  expand = "eva:expand-outline",
  clock = "eva:clock-fill",
  list = "eva:list-outline",
  close = "eva:close-outline",
  search = "eva:search-outline",
  arrowLink = "eva:diagonal-arrow-right-up-fill",
}

export default Icons;
